[package]
name = "ixgbe-driver"
version = "0.1.0"
edition = "2021"
authors = ["Ramla <ijazramla@gmail.com>", "KuangjuX <kuangjux@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
